language: scala
jdk:
  - oraclejdk8
scala:
  - "2.11.7"
before_install:
  - mkdir /tmp/dynamodb
  - wget -O - http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz | tar xzC /tmp/dynamodb
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -Xss1m -Xms320m -Xmx320m -jar /tmp/dynamodb/DynamoDBLocal.jar -inMemory &
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties"
